# -*- coding: utf-8 -*-
"""QBP Price Calculator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MrqKPC4oX62-OLN48OEIXUKQhensIunA
"""

def calcPrice():

    price = float(input("Enter price of item\n"))
    msrp = float(input("Enter MSRP of item\n"))
    employee = input("Is this item for an employee? (y/n)\n")

    if price <= 99.99:
        adjPrice = float(price * 2)

    else:
        adjPrice = float(price * 1.6)


    if employee == "y":
        if adjPrice < msrp:
            finalPrice = float(adjPrice * 0.7)

        else:
            finalPrice = float(msrp * 0.7)

    else:
        finalPrice = msrp

    print(f"${finalPrice:.2f} is what you would pay")

calcPrice()